require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/book_checkouts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BookCheckout. As you add validations to BookCheckout, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BookCheckout.create! valid_attributes
      get book_checkouts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      book_checkout = BookCheckout.create! valid_attributes
      get book_checkout_url(book_checkout)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_book_checkout_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      book_checkout = BookCheckout.create! valid_attributes
      get edit_book_checkout_url(book_checkout)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BookCheckout" do
        expect {
          post book_checkouts_url, params: { book_checkout: valid_attributes }
        }.to change(BookCheckout, :count).by(1)
      end

      it "redirects to the created book_checkout" do
        post book_checkouts_url, params: { book_checkout: valid_attributes }
        expect(response).to redirect_to(book_checkout_url(BookCheckout.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BookCheckout" do
        expect {
          post book_checkouts_url, params: { book_checkout: invalid_attributes }
        }.to change(BookCheckout, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post book_checkouts_url, params: { book_checkout: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested book_checkout" do
        book_checkout = BookCheckout.create! valid_attributes
        patch book_checkout_url(book_checkout), params: { book_checkout: new_attributes }
        book_checkout.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the book_checkout" do
        book_checkout = BookCheckout.create! valid_attributes
        patch book_checkout_url(book_checkout), params: { book_checkout: new_attributes }
        book_checkout.reload
        expect(response).to redirect_to(book_checkout_url(book_checkout))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        book_checkout = BookCheckout.create! valid_attributes
        patch book_checkout_url(book_checkout), params: { book_checkout: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested book_checkout" do
      book_checkout = BookCheckout.create! valid_attributes
      expect {
        delete book_checkout_url(book_checkout)
      }.to change(BookCheckout, :count).by(-1)
    end

    it "redirects to the book_checkouts list" do
      book_checkout = BookCheckout.create! valid_attributes
      delete book_checkout_url(book_checkout)
      expect(response).to redirect_to(book_checkouts_url)
    end
  end
end
